/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as CaRouteImport } from './routes/ca'
import { Route as CloseDayRouteImport } from './routes/close-day'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoinRouteImport } from './routes/join'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShopEditRouteImport } from './routes/shop-edit'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StockInRouteImport } from './routes/stock-in'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as BillsSaleIdRouteImport } from './routes/bills.$saleId'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffStaffIdRouteImport } from './routes/staff.$staffId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const CaRoute = CaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => rootRouteImport,
} as any)
const CloseDayRoute = CloseDayRouteImport.update({
  id: '/close-day',
  path: '/close-day',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopEditRoute = ShopEditRouteImport.update({
  id: '/shop-edit',
  path: '/shop-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StockInRoute = StockInRouteImport.update({
  id: '/stock-in',
  path: '/stock-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillsRoute,
} as any)
const BillsSaleIdRoute = BillsSaleIdRouteImport.update({
  id: '/$saleId',
  path: '/$saleId',
  getParentRoute: () => BillsRoute,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRouteWithChildren
  '/ca': typeof CaRoute
  '/close-day': typeof CloseDayRoute
  '/connect': typeof ConnectRoute
  '/crm': typeof CrmRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/review': typeof ReviewRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/shop-edit': typeof ShopEditRoute
  '/staff': typeof StaffRouteWithChildren
  '/stock': typeof StockRoute
  '/stock-in': typeof StockInRoute
  '/suppliers': typeof SuppliersRoute
  '/tools': typeof ToolsRoute
  '/whatsapp': typeof WhatsappRoute
  '/bills/$saleId': typeof BillsSaleIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/bills/': typeof BillsIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/close-day': typeof CloseDayRoute
  '/connect': typeof ConnectRoute
  '/crm': typeof CrmRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/review': typeof ReviewRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/shop-edit': typeof ShopEditRoute
  '/stock': typeof StockRoute
  '/stock-in': typeof StockInRoute
  '/suppliers': typeof SuppliersRoute
  '/tools': typeof ToolsRoute
  '/whatsapp': typeof WhatsappRoute
  '/bills/$saleId': typeof BillsSaleIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/bills': typeof BillsIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRouteWithChildren
  '/ca': typeof CaRoute
  '/close-day': typeof CloseDayRoute
  '/connect': typeof ConnectRoute
  '/crm': typeof CrmRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/review': typeof ReviewRoute
  '/sell': typeof SellRoute
  '/shop': typeof ShopRoute
  '/shop-edit': typeof ShopEditRoute
  '/staff': typeof StaffRouteWithChildren
  '/stock': typeof StockRoute
  '/stock-in': typeof StockInRoute
  '/suppliers': typeof SuppliersRoute
  '/tools': typeof ToolsRoute
  '/whatsapp': typeof WhatsappRoute
  '/bills/$saleId': typeof BillsSaleIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/bills/': typeof BillsIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/ca'
    | '/close-day'
    | '/connect'
    | '/crm'
    | '/help'
    | '/join'
    | '/orders'
    | '/profile'
    | '/returns'
    | '/review'
    | '/sell'
    | '/shop'
    | '/shop-edit'
    | '/staff'
    | '/stock'
    | '/stock-in'
    | '/suppliers'
    | '/tools'
    | '/whatsapp'
    | '/bills/$saleId'
    | '/pay/$token'
    | '/staff/$staffId'
    | '/bills/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ca'
    | '/close-day'
    | '/connect'
    | '/crm'
    | '/help'
    | '/join'
    | '/orders'
    | '/profile'
    | '/returns'
    | '/review'
    | '/sell'
    | '/shop'
    | '/shop-edit'
    | '/stock'
    | '/stock-in'
    | '/suppliers'
    | '/tools'
    | '/whatsapp'
    | '/bills/$saleId'
    | '/pay/$token'
    | '/staff/$staffId'
    | '/bills'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/ca'
    | '/close-day'
    | '/connect'
    | '/crm'
    | '/help'
    | '/join'
    | '/orders'
    | '/profile'
    | '/returns'
    | '/review'
    | '/sell'
    | '/shop'
    | '/shop-edit'
    | '/staff'
    | '/stock'
    | '/stock-in'
    | '/suppliers'
    | '/tools'
    | '/whatsapp'
    | '/bills/$saleId'
    | '/pay/$token'
    | '/staff/$staffId'
    | '/bills/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRouteWithChildren
  CaRoute: typeof CaRoute
  CloseDayRoute: typeof CloseDayRoute
  ConnectRoute: typeof ConnectRoute
  CrmRoute: typeof CrmRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ReturnsRoute: typeof ReturnsRoute
  ReviewRoute: typeof ReviewRoute
  SellRoute: typeof SellRoute
  ShopRoute: typeof ShopRoute
  ShopEditRoute: typeof ShopEditRoute
  StaffRoute: typeof StaffRouteWithChildren
  StockRoute: typeof StockRoute
  StockInRoute: typeof StockInRoute
  SuppliersRoute: typeof SuppliersRoute
  ToolsRoute: typeof ToolsRoute
  WhatsappRoute: typeof WhatsappRoute
  PayTokenRoute: typeof PayTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca': {
      id: '/ca'
      path: '/ca'
      fullPath: '/ca'
      preLoaderRoute: typeof CaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/close-day': {
      id: '/close-day'
      path: '/close-day'
      fullPath: '/close-day'
      preLoaderRoute: typeof CloseDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-edit': {
      id: '/shop-edit'
      path: '/shop-edit'
      fullPath: '/shop-edit'
      preLoaderRoute: typeof ShopEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-in': {
      id: '/stock-in'
      path: '/stock-in'
      fullPath: '/stock-in'
      preLoaderRoute: typeof StockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof BillsRoute
    }
    '/bills/$saleId': {
      id: '/bills/$saleId'
      path: '/$saleId'
      fullPath: '/bills/$saleId'
      preLoaderRoute: typeof BillsSaleIdRouteImport
      parentRoute: typeof BillsRoute
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface BillsRouteChildren {
  BillsSaleIdRoute: typeof BillsSaleIdRoute
  BillsIndexRoute: typeof BillsIndexRoute
}

const BillsRouteChildren: BillsRouteChildren = {
  BillsSaleIdRoute: BillsSaleIdRoute,
  BillsIndexRoute: BillsIndexRoute,
}

const BillsRouteWithChildren = BillsRoute._addFileChildren(BillsRouteChildren)

interface StaffRouteChildren {
  StaffStaffIdRoute: typeof StaffStaffIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffIdRoute: StaffStaffIdRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRouteWithChildren,
  CaRoute: CaRoute,
  CloseDayRoute: CloseDayRoute,
  ConnectRoute: ConnectRoute,
  CrmRoute: CrmRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ReturnsRoute: ReturnsRoute,
  ReviewRoute: ReviewRoute,
  SellRoute: SellRoute,
  ShopRoute: ShopRoute,
  ShopEditRoute: ShopEditRoute,
  StaffRoute: StaffRouteWithChildren,
  StockRoute: StockRoute,
  StockInRoute: StockInRoute,
  SuppliersRoute: SuppliersRoute,
  ToolsRoute: ToolsRoute,
  WhatsappRoute: WhatsappRoute,
  PayTokenRoute: PayTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
